- name: reload haproxy service
  shell: "systemctl daemon-reload"
  when: (ansible_distribution == "CentOS" or ansible_os_family == "RedHat") and ansible_distribution_major_version | int == 7

- name: start haproxy service
  service:
    name: haproxy
    state: started
    enabled: yes