- name: create nginx logs
  file:
    path: "{{ item }}"
    state: touch
    mode: 0766
  with_items:
    - "{{ nginx_install_dir }}/logs/error.log"
    - "{{ nginx_install_dir }}/logs/access.log"

- name: change nginx install directory property
  file:
    path: "{{ nginx_install_dir }}"
    recurse: yes
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: reload nginx service
  shell: "systemctl daemon-reload"
  when: (ansible_distribution == "CentOS" or ansible_os_family == "RedHat") and ansible_distribution_major_version | int == 7

- name: start nginx
  service:
    name: nginx
    enabled: yes
    state: restarted