---
#
# Description: 
#     用于控制源码编译安装 zabbix_agentd 的参数
#

# 是否依赖角色 common 
dependency_common: false

# 安装方式：packageManager(yum|dnf) | compileSource 
install_type: compileSource

zabbix_agentd_user: zabbix
zabbix_agentd_group: zabbix
zabbix_agentd_port: 30050

zabbix_agentd_install_dir: "/usr/local/zabbix_agentd"
zabbix_agentd_logs_dir: "{{ zabbix_agentd_install_dir }}/logs"
zabbix_conf_dir: "{{ zabbix_agentd_install_dir }}/etc"

# zabbix_agentd 的模式：active or passive
# 默认为 主动 active
zabbix_agentd_model: active 

# 是否 使用 proxy
zabbix_proxy: false
# 当 zabbix_proxy 为 true 时，需要设置  zabbix_proxy_ip 的地址
zabbix_proxy_ip: ""

zabbix_server_ip: 127.0.0.1
zabbix_server_port: 10051

zabbix_source_code: zabbix-3.4.15.tar.gz

# 目前官网可选: 
# zabbix-release-4.0-1.el6.noarch.rpm 
# zabbix-release-3.0-1.el7.noarch.rpm
# zabbix-release-2.2-1.el6.noarch.rpm

zabbix_version: zabbix-release-3.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
# 基于 CentOS/RedHat 的官网 repository url
zabbix_repository_url: https://repo.zabbix.com/zabbix/3.0/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/{{ zabbix_version}}

# https://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
# https://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm

# 是否启用 agentd 和 server 的相互 ca 认证
is_certificate: false