# 设置主机之间免密码登陆、主机名和 ip 地址对应关系
- name: template free password login file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "password_free_login.txt.j2", dest: "{{ remote_temp_dir }}/password_free_login.txt", mode: "0644" }
    - { src: "SetupFreePassword.sh.j2", dest: "{{ remote_temp_dir }}/SetupFreePassword.sh", mode: "0755" }

- name: set password free login
  shell: sh "{{ remote_temp_dir }}/SetupFreePassword.sh" "{{ remote_temp_dir }}/password_free_login.txt"
  register: shell_result
  when: ansible_env.SHELL == "/bin/bash"

- name: setup ip switch to hostname
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root

- name: set hostname on {{ ansible_distribution }}-{{ ansible_distribution_major_version }}
  shell: hostname {{ name }} && echo -e "NETWORKING=yes\nHOSTNAME={{ name }}" > /etc/sysconfig/network
  when: (ansible_distribution == "CentOS" or ansible_os_family == "RedHat") and ansible_distribution_major_version | int == 6

- name: set hostname on {{ ansible_distribution }}-{{ ansible_distribution_major_version }}
  shell: hostnamectl set-hostname {{ name }}
  when: (ansible_distribution == "CentOS" or ansible_os_family == "RedHat") and ansible_distribution_major_version | int == 7

- name: delete related files
  file:
      path: "{{ item }}"
      state: absent
      force: yes
  with_items:
    - "{{ remote_temp_dir }}/SetupFreePassword.sh"
    - "{{ remote_temp_dir }}/password_free_login.txt"