- name: add repository to {{ ansible_distribution }}-{{ ansible_distribution_major_version }}
  template:
    src: "docker-ce.repo.j2"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "CentOS" or ansible_os_family == "RedHat"

- name: uninstalled old docker
  yum:
    name:
      - docker
      - docker-common
      - docker-selinux
      - docker-engine
    state: absent
  when: ansible_distribution == "CentOS" or ansible_os_family == "RedHat"

# 默认安装 repo 中的最新版本
# 在命令行中可以执行: 
# yum list docker-ce --showduplicates | sort -r
# yum intsall <FQPN>
- name: install required packages for docker
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
  when: ansible_distribution == "CentOS" or ansible_os_family == "RedHat"