---
#
# Description: configure php
#

- name: template php configure files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    # 配置文件
    - { src: "php.ini.j2", dest: "{{ php_conf_dir }}/php.ini" }
    - { src: "php-fpm.conf.j2", dest: "{{ php_conf_dir }}/php-fpm.conf" }

- name: set php-fpm self boot
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "php-fpm.sh.j2", dest: "/etc/init.d/php-fpm", mode: "0755", os_family: "RedHat", os_version: "6" }
    - { src: "php-fpm.service.j2", dest: "/usr/lib/systemd/system/php-fpm.service", mode: "0755", os_family: "RedHat", os_version: "7" }
  when: item.os_family == ansible_os_family and item.os_version == ansible_distribution_major_version

- name: modify php installation property
  file:
    path: "{{ php_install_dir }}"
    recurse: yes
    owner: root
    group: root

- name: setup php environment variables
  template:
    src: "set_php_environment_variables.sh.j2"
    dest: "/etc/profile.d/php.sh"
    mode: 0644
    owner: root
    group: root