- name: touch mysql log
  file:
    path: "{{ item.path }}"
    state: touch
    mode: "u=rw,g=rw,o=r"
  with_items:
    - { path: "{{ mysql_logs_dir }}/mysql-error.log" }
    - { path: "{{ mysql_logs_dir }}/mysql-slow.log" }

- name: change mysql directory property
  file:
    path: "{{ item.path }}"
    recurse: yes
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: "{{ mysql_install_dir }}", mode: "0755" }

- name: delete error data directory
  file:
    path: "{{ mysql_data_dir }}"
    state: absent

# 初始化 mysql, 创建 data 数据目录
- name: initial mysql data directory
  command: 
    "{{ mysql_install_dir }}/bin/mysqld --initialize --user={{ mysql_user }} --basedir={{ mysql_install_dir }} --datadir={{ mysql_data_dir }}"
  register: initial_result

- name: start mysql on {{ ansible_distribution }}-{{ ansible_distribution_major_version}}
  service:
    name: mysqld
    state: "started"
    enabled: yes
  when: (ansible_distribution == "CentOS" or ansible_os_family == "RedHat") and ansible_distribution_major_version | int == 6

- name: start mysql on {{ ansible_distribution }}-{{ ansible_distribution_major_version }}
  shell: "{{ item }}"
  with_items:
    - "/usr/sbin/chkconfig --level 345 --add mysqld"
    - "/usr/sbin/chkconfig mysqld on" 
    - "/usr/sbin/service mysqld start"
  when: (ansible_distribution == "CentOS" or ansible_os_family == "RedHat") ansible_distribution_major_version | int == 7

