- name: create {{ squid_group }} group 
  group:
    name: "{{ squid_group }}"
    system: yes
    state: present

- name: create {{ squid_user }} user
  user:
    name: "{{ squid_user }}"
    comment: "squid proxy user"
    create_home: no
    system: yes
    state: present
    shell: /usr/bin/false
    group: "{{ squid_group }}"

- name: create cache and log directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ squid_cache_dir }}"
    - "{{ squid_log_dir }}"
    - "{{ squid_run_dir }}"

- name: template squid's config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: "squid.conf.j2", dest: "{{ squid_config_dir }}/squid.conf", mode: "0644" }
    - { src: "squid_environment_file.j2", dest: "{{ squid_config_dir }}/squid", mode: "0644" }
    - { src: "cache_swap.sh.j2", dest: "{{ squid_config_dir }}/cache_swap.sh", mode: "0755" }
    - { src: "squid_pam.j2", dest: "/etc/pam.d/squid", mode: "0644" }
    - { src: "squid_logrotate.j2", dest: "/etc/logrotate.d/squid", mode: "0644" }

- name: template squid boot file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: "squid.sh.j2", dest: "/etc/init.d/squid", mode: "0755", os_distribution: "CentOS", os_major_version: "6" }
    - { src: "squid.service.j2", dest: "/usr/lib/systemd/system/squid.service", mode: "0644", os_distribution: "CentOS", os_major_version: "7" }
  when: ansible_distribution == item.os_distribution and ansible_distribution_major_version == item.os_major_version

- name: Modify properties of {{ squid_install_dir }} directory
  file:
    path: "{{ squid_install_dir }}"
    recurse: yes
    owner: "{{ squid_user }}"
    group: "{{ squid_group }}"