- name: reload squid.service
  shell: systemctl daemon-reload
  when: ( ansible_distribution == "CentOS" or ansible_os_family == "RedHat" ) and ansible_distribution_major_version | int == 7

- name: start squid.service
  service:
    name: squid
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS" or ansible_os_family == "RedHat"